### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by mbebiano** [anirudhbagri/whatsapp-bulk-messenger#1]
Hello, I was banned from whatsapp. I believe it is easy to detect selenium through the browser

**Comment by anirudhbagri** [comment]
How many messages were you sending? Were you sending it to just 1 number?

**Comment by mbebiano** [comment]
So, I had programmed to send 150 numbers at 13 second intervals. For unknown numbers. I believe that if he had added the contact list he might not have been banned. I intend to do new tests, send a single message to 200 unknown numbers for 8 hours. I saw solutions in JS, maybe they are more efficient, in the whatsapp api itself just changing the number, what do you think? Do you have any experience with this ban interval?

Note: It was a direct ban, not a temporary one. I had to resort to support to check

**Comment by anirudhbagri** [comment]
Yes, please let me know the result of another test. I have never faced this ban issue, so can't help with the ban interval. 
Could you lead me to where you saw JS solution.
I have also previously worked on a JS solution and sent message to over 900 numbers without ban. But it was slow and took 45 seconds to send to a single number.
However, I have not uploaded that in my repo.

**Comment by mbebiano** [comment]
Okay, I'll keep you posted. Finding some solution in JS I send you here, thanks.

**Comment by anirudhbagri** [comment]
Hi @mbebiano,

What do you think about the ban issue now? Does it still happen?
Did you get any JS solution to this?
