### ISSUE TITLE
Sending images 

### ISSUE THREAD

**Issue by sbhadade** [anirudhbagri/whatsapp-bulk-messenger#10]
how to send images through message sender ?

**Comment by Depter30** [comment]
> how to send images through message sender ?

I have same question. Pls help

**Comment by anirudhbagri** [comment]
drop me an email (you can get it from readme), I have another app which can doing this.

**Comment by anirudhbagri** [comment]
Closing this.

It is not supported yet, and there is no plan as of now. Please check the note in `readme` file for more info.
