### ISSUE TITLE
Bypass if a number is not active

### ISSUE THREAD

**Issue by himanshurajiv** [anirudhbagri/whatsapp-bulk-messenger#13]
I am a noob in programming, but I could actually run the script and send particular messages to my contacts (over 1000 contacts, therefore using script). 
My problem is that a lot of numbers in my contact lists don't have whatsapp with their numbers. This creates an issue as the program stops and then I have to manually click on whatsapp interface and then press enter on the command line. Can you suggest how one can bypass this?

**Comment by anirudhbagri** [comment]
If you leave it as it is.. it will automatically fail and move to next number in 30 secs or so.

**Comment by himanshurajiv** [comment]
It shows this error and stops

Press enter to continue[20496:17436:1104/092400.089:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by anirudhbagri** [comment]
Hi @himanshurajiv - On a side note.. checkout this [video](https://www.youtube.com/watch?v=NNkAh5sLEok) as it might help you with what you are looking for.

**Comment by himanshurajiv** [comment]
Hi @anirudhbagri : Thanks a lot for the link. 
In my case, I just commented out line 71 of the code and then left it in peace. I didn't had to click on the keyboard to resume the script anymore. Just worked perfectly.  Great code btw. Highly efficient.

**Comment by anirudhbagri** [comment]
Thanks @himanshurajiv!
Glad to hear that :)
