### ISSUE TITLE
How Add Image In Message

### ISSUE THREAD

**Issue by PrashantMeenaa** [anirudhbagri/whatsapp-bulk-messenger#21]
HI, i want to send image with message but, this script sending message using text document. how can we add image in message to send with text.

**Comment by anirudhbagri** [comment]
There is a separate app which does send image and documents. 
Email me to get more info.

**Comment by PrashantMeenaa** [comment]
> 
your email please

**Comment by ChaitanyaYeole02** [comment]
I also want to send an Image with a text
