### ISSUE TITLE
Failed to send message to 'phone-number'

### ISSUE THREAD

**Issue by sainirahulove** [anirudhbagri/whatsapp-bulk-messenger#3]
I have chrome V86 so I replaced google driver version to V86 but when I run the Command  I get this log in command 
`DevTools listening on ws://127.0.0.1:57226/devtools/browser/aa42d0f7-2ee7-4465-b654-a18e1479024b
[6700:1244:1101/100847.869:ERROR:device_event_log_impl.cc(208)] [10:08:47.868] Bluetooth: bluetooth_adapter_winrt.cc:1076 Getting Default Adapter failed.`

But everything goes well after pressing the enter button Whatsapp chat opens with message and after delay of 30 sec, this error message pops in command  
`Failed to send message to #phone number`

**Comment by anirudhbagri** [comment]
@sainirahulove, did you run the app as administrator? If not, can you try running that as admin?

**Comment by anirudhbagri** [comment]
Closing this, as it is not reproducible. 
Fell free to open again if the error appears again.
