### ISSUE TITLE
what if the number is not valide ?

### ISSUE THREAD

**Issue by m7jalta** [anirudhbagri/whatsapp-bulk-messenger#6]
the script is working when the number is valide but when a number is not whatsapp is showing a message with ok button! 
i tried to fix that with : 
from selenium.webdriver import ActionChains

ActionChains(browser).click(element).perform()

but i am getting some errors 

nb: i tried click but class but not working

**Comment by anirudhbagri** [comment]
Let the script run as it is, it will automatically move to the next number after trying thr invalid number in next 30 seconds.

**Comment by anirudhbagri** [comment]
It's a known issue, fix is coming soon.

**Comment by anirudhbagri** [comment]
Hi @m7jalta,

Did the 30-second wait trick worked for you?
