### ISSUE TITLE
Messages not sending

### ISSUE THREAD

**Issue by drtamakloe** [anirudhbagri/whatsapp-bulk-messenger#7]
First of all, thank you for making this great code. You are a genius.

I have a problem. In my case, the code runs fine. But whatsapp opens, lads the message but it never gets sent. How do I deal with this issue?

**Comment by anirudhbagri** [comment]
Hi @drtamakloe, do you see any exception in logs?

**Comment by drtamakloe** [comment]
Not at all. There wasnt any exception. The messages failed to send even on the third try after whatsapp opens

**Comment by anirudhbagri** [comment]
That is weird.

**Comment by anirudhbagri** [comment]
There is no path to go except an `exception` or `successful`. Interesting.

**Comment by anirudhbagri** [comment]
@drtamakloe, Can you pull the latest changes and try?
I think I got the issue.

**Comment by anirudhbagri** [comment]
Closing this as I have not received any update. 
Please re-open if you are still facing the same issue.

**Comment by tammabank** [comment]
am unable to send the messages , it just fails after 3 restries.
